version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: todolist-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: todolist
    volumes:
      - mongodb_data:/data/db
    networks:
      - todolist-network

  # TodoList Application
  todolist-app:
    image: geetasree0103/todolist-app:latest
    container_name: todolist-application
    ports:
      - "8080:8080"
    environment:
      # MongoDB connection settings
      SPRING_DATA_MONGODB_URI: mongodb://admin:password123@mongodb:27017/todolist?authSource=admin
      SPRING_DATA_MONGODB_DATABASE: todolist
    depends_on:
      - mongodb
    networks:
      - todolist-network

volumes:
  mongodb_data:

networks:
  todolist-network:
    driver: bridge



